################################################################################
# Copyright 2021 highstreet technologies GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
version: '3.8'

x-common_env: &common_env
    IPv6_ENABLED: ${IPv6_ENABLED}
    SSH_CONNECTIONS: ${SSH_CONNECTIONS}
    TLS_CONNECTIONS: ${TLS_CONNECTIONS}    
    NTS_NF_MOUNT_POINT_ADDRESSING_METHOD: ${NTS_NF_MOUNT_POINT_ADDRESSING_METHOD}
    
    NTS_HOST_IP: ${NTS_HOST_IP}
    NTS_HOST_BASE_PORT: ${NTS_HOST_BASE_PORT}
    NTS_HOST_NETCONF_SSH_BASE_PORT: ${NTS_HOST_NETCONF_SSH_BASE_PORT}
    NTS_HOST_NETCONF_TLS_BASE_PORT: ${NTS_HOST_NETCONF_TLS_BASE_PORT}
    NTS_HOST_TRANSFER_FTP_BASE_PORT: ${NTS_HOST_TRANSFER_FTP_BASE_PORT}
    NTS_HOST_TRANSFER_SFTP_BASE_PORT: ${NTS_HOST_TRANSFER_SFTP_BASE_PORT}
    
    SDN_CONTROLLER_PROTOCOL: ${SDN_CONTROLLER_PROTOCOL}
    SDN_CONTROLLER_IP: ${SDNC_OAM_IPv6}
    SDN_CONTROLLER_PORT: ${SDNC_REST_PORT}
    SDN_CONTROLLER_CALLHOME_PORT: ${SDN_CONTROLLER_CALLHOME_PORT}
    SDN_CONTROLLER_USERNAME: ${ADMIN_USERNAME}
    SDN_CONTROLLER_PASSWORD: ${ADMIN_PASSWORD}
    
    VES_COMMON_HEADER_VERSION: ${VES_COMMON_HEADER_VERSION}
    VES_ENDPOINT_PROTOCOL: ${VES_ENDPOINT_PROTOCOL}
    VES_ENDPOINT_IP: ${VES_COLLECTOR_OAM_IPv6}
    VES_ENDPOINT_PORT: ${VES_ENDPOINT_PORT}
    VES_ENDPOINT_AUTH_METHOD: ${VES_ENDPOINT_AUTH_METHOD}
    VES_ENDPOINT_USERNAME: ${VES_ENDPOINT_USERNAME}
    VES_ENDPOINT_PASSWORD: ${VES_ENDPOINT_PASSWORD}

x-du_env: &du_env
    NTS_NF_STANDALONE_START_FEATURES: "datastore-populate ves-heartbeat ves-file-ready ves-pnf-registration web-cut-through"

x-ru-env: &ru_env
    NTS_NF_STANDALONE_START_FEATURES: "datastore-populate netconf-call-home web-cut-through"

x-topo-env: &topo_env
    NTS_NF_STANDALONE_START_FEATURES: "datastore-populate netconf-call-home web-cut-through"

x-nf: &common_nf
    stop_grace_period: 5m
    cap_add:
    - SYS_ADMIN
    - SYS_PTRACE

services:
  ntsim-ng-o-enb:
    <<: *common_nf
    container_name: srsRAN_o-eNB
    hostname: o-eNB
    build: .
    ports:
       - "2002:2002/tcp"
    #command: >
    #   sh -c "route add -host 10.7.1.2 eth0; /bin/bash"
    networks:
      default:
      ran01:
        ipv4_address: 10.6.1.2
      ue01:
        ipv4_address: 10.8.1.2
    volumes:
        - ./config.json:/opt/dev/ntsim-ng/config/config.json
        - ./config_fault.json:/opt/dev/ntsim-ng/config/config_fault.json
        - ./data/o-ran-sc-du-hello-world-running.xml:/opt/dev/deploy/data/o-ran-sc-du-hello-world-running.xml
        - ./data/o-ran-sc-du-hello-world-operational.xml:/opt/dev/deploy/data/o-ran-sc-du-hello-world-operational.xml
    environment:
        <<: *common_env
        <<: *du_env
    tty: true
    stdin_open: true
    privileged: true

  srsue:
    hostname: srsue
    container_name: srsue01
    build: .
    ports:
       - "2004:2004/tcp"
    networks:
      ue01:
        ipv4_address: 10.8.1.4
    tty: true
    stdin_open: true
    privileged: true
  srsepc:
    hostname: srsepc
    container_name: srsepc01
    build: .
    ports:
       - "2003:2003/tcp"
    command: >
       sh -c "route add -host 10.6.1.2 eth0 &&
              route del default &&
              route add default gw 10.9.1.1 &&
              iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE; /bin/bash"
    networks:
      default:
      core01:
        ipv4_address: 10.7.1.2
      sgi01:
        ipv4_address: 10.9.1.2
      sgi02:
        ipv4_address: 10.9.2.2
    tty: true
    stdin_open: true
    privileged: true

networks:
  default:
    external:
      name: oam
  core01:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.7.1.0/24
  ran01:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.6.1.0/24
  ue01:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.8.1.0/24
  sgi01:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.9.1.0/24
  sgi02:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.9.2.0/24